# Vagrant file for launching multiple Ubuntu VM's for user training

BOX_IMAGE = "ubuntu/bionic64"
NODE_COUNT = 6

Vagrant.configure("2") do |config|

  (1..NODE_COUNT).each do |i|
    config.vm.define "ws0#{i}" do |node|
      node.vm.box_check_update = true
      node.vm.box = BOX_IMAGE
      node.vm.box_version = "20191206.0.0"
      node.vm.hostname = "ws0#{i}"
      node.vm.provision "shell", path: "bootstrap.sh"
	  node.vm.network "public_network", auto_config: false
    end
  end

  config.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
	 vb.cpus = "2"
  end
  
end
